## The NumPy Array

In [51]:
import numpy as np

In [52]:
a = np.array([1, 2, 3])
a + a
# output array([2, 4, 6])

array([2, 4, 6])

In [53]:
def print_array_details(a):
    print('Dimensions: %d, shape: %s, dtype: %s'%(a.ndim, a.shape, a.dtype))

In [54]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
print_array_details(a)

Dimensions: 1, shape: (8,), dtype: int64


In [56]:
a = a.reshape([2, 4])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
print_array_details(a)

Dimensions: 2, shape: (2, 4), dtype: int64


In [58]:
a = a.reshape([2, 2, 2])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [59]:
print_array_details(a)

Dimensions: 3, shape: (2, 2, 2), dtype: int64


In [60]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
x.shape

(2, 3)

In [61]:
x.shape = (6,)
x

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [62]:
x = x.astype('int64')
x.dtype

dtype('int64')

## Creating Arrays

In [63]:
a = np.zeros([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [64]:
a.dtype

dtype('float64')

In [65]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
empty_array = np.empty((2,3))
empty_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.random.random((2,3))

array([[0.43672546, 0.71583728, 0.36674738],
       [0.27810285, 0.77284775, 0.72972499]])

In [68]:
np.linspace(2, 10, 5) # 5 numbers in range 2-10

array([ 2.,  4.,  6.,  8., 10.])

In [69]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

## Array Indexing and Slicing

In [70]:
a = np.array([1, 2, 3, 4, 5, 6])
a[2]

3

In [71]:
a[3:5]

array([4, 5])

In [72]:
# every second item from 0-4 set to 0
a[:4:2] = 0
a

array([0, 2, 0, 4, 5, 6])

In [73]:
a[::-1]

array([6, 5, 4, 0, 2, 0])

In [74]:
# use of full selection (:) and ellipsis
a = np.arange(8)
a.shape = (2, 2, 2)
a
#a[...,0] == a[:,:,0]

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [75]:
a1 = a[1].copy()
a1

array([[4, 5],
       [6, 7]])

In [76]:
a2 = a[1,:].copy()
a2

array([[4, 5],
       [6, 7]])

In [77]:
a3 = a[1,:,:].copy()
a3

array([[4, 5],
       [6, 7]])

In [78]:
# a quick test of equality - the array_equal method compares by shape and elements
np.array_equal(a1, a2)

True

In [79]:
np.array_equal(a1, a3)

True

In [80]:
np.array_equal(a1, a[1,:])

True

In [81]:
a[...,0]

array([[0, 2],
       [4, 6]])

In [82]:
np.array_equal(a[...,0], a[:,:,0])

True

## A Few Basic Operations

In [83]:
a = np.array([45, 65, 76, 32, 99, 22])
a < 50

array([ True, False, False,  True, False,  True])

In [84]:
# Some array methods
a = np.arange(8).reshape((2,4))
# array([[0, 1, 2, 3],
# [4, 5, 6, 7]])
a.min(axis=1)
# array([0, 4])
a.sum(axis=0)
# array([4, 6, 8, 10])
a.mean(axis=1)
# array([ 1.5, 5.5 ])
a.std(axis=1)
# array([ 1.11803399, 1.11803399])

array([1.11803399, 1.11803399])

In [85]:
a.min(axis=1)

array([0, 4])

In [86]:
a.sum(axis=0)

array([ 4,  6,  8, 10])

In [87]:
a.mean(axis=1)

array([1.5, 5.5])

In [88]:
a.std(axis=1)

array([1.11803399, 1.11803399])

In [89]:
# Trigonometric functions
pi = np.pi
a = np.array([pi, pi/2, pi/4, pi/6])
np.degrees(a) # radians to degrees

array([180.,  90.,  45.,  30.])

In [90]:
sin_a = np.sin(a)
sin_a

array([1.22464680e-16, 1.00000000e+00, 7.07106781e-01, 5.00000000e-01])

In [91]:
np.round(sin_a, 7) # round to 7 decimal places

array([0.       , 1.       , 0.7071068, 0.5      ])

In [92]:
# Sums, products, differences
a = np.arange(8).reshape((2,4))
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [93]:
np.cumsum(a, axis=1) # cumulative sum along second axis

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22]])

In [94]:
np.cumsum(a) # without axis argument, array is flattened

array([ 0,  1,  3,  6, 10, 15, 21, 28])

# Creating Array Functions

## Calculating a Moving Average

In [95]:
# Calculate a moving average with window size n
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

In [96]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [97]:
csum = np.cumsum(a)
csum

array([ 0,  1,  3,  6, 10, 15])

In [98]:
csum[3:] = csum[3:] - csum[:-3]
csum

array([ 0,  1,  3,  6,  9, 12])

In [99]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
moving_average(a, 4)

array([1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5])